version: '3'
services:
  web:
    build: .
    environment:
      - "DJANGO_SETTINGS_MODULE=cove_ocds.settings"
      - "ALLOWED_HOSTS=localhost"
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
